### ISSUE TITLE
Segfault error when running pratchet

### ISSUE THREAD

**Issue by kbhoehn** [KlausVigo/phangorn#116]
Hello, thanks for fixing the previous bug with pratchet. However, after updating phangorn I'm now sometimes getting segfault errors with pratchet that cause my R session to crash. I've been able to reproduce them with the following example:

data = phangorn::phyDat(ape::as.DNAbin(
rbind(
"GN5SHBT06FWLD3"=c("C","A","A","C"), 
"GN5SHBT02ELSDQ"=c("C","A","A","C"), 
"GN5SHBT05HKY8M"=c("C","A","G","C"), 
"GN5SHBT06HL7IW"=c("C","A","A","C"),
"GN5SHBT08IUH22"=c("C","A","G","C"),
"GN5SHBT06HL7IW"=c("C","A","A","C")
)))

phangorn::pratchet(data,trace=FALSE)

Results in:
 *** caught segfault ***
address 0x28, cause 'memory not mapped'

Traceback:
 1: fastme.ols(dist.hamming(data))
 2: optim.fitch(tree = tree, data = data, trace = trace, rearrangements = rearrangements,     ...)
 3: optim.parsimony(fastme.ols(dist.hamming(data)), data, trace = trace -     1, method = method, rearrangements = rearrangements, ...)
 4: phangorn::pratchet(data, trace = FALSE)

In other cases I've gotten the error message:
"Error in f$pscore_nni(INDEX[, 1L:4L]) : Not a matrix."

Or an out-of-bounds error. I can send those examples as well, though I suspect they're related. I'm using R 4.0.4.

**Comment by KlausVigo** [comment]
Hi @kbhoehn, 
thanks for reporting this. It is now fixed on github. The error was introduced as I started removing more parsimonious uniformative sites and duplicated sequences. For this dataset a multifurcating tree is returned and the data perfectly fits on a tree. It requires the new ape version (>=5.5).
Regards, 
Klaus

**Comment by KlausVigo** [comment]
Hi @kbhoehn, 
a new version in on CRAN now with this fix.
Regards, 
Klaus

**Comment by kbhoehn** [comment]
Hi @KlausVigo - thanks for fixing that error! I've been using the new version but it seems like I'm still getting a remaining error message:

Error in f$pscore_nni(INDEX[, 1L:4L]) : Not a matrix.

It doesn't happen every time I run pratchet, but is quite frequent. I've attached the sequences used to get this bug in fasta format here:
[data.txt](https://github.com/KlausVigo/phangorn/files/6423360/data.txt)

Thanks again for your help! I've found phangorn really useful otherwise.
Best,
-Ken

The traceback is:

7: stop(structure(list(message = "Not a matrix.", call = f$pscore_nni(INDEX[, 
       1L:4L]), cppstack = NULL), class = c("Rcpp::not_a_matrix", 
   "C++Error", "error", "condition")))
6: .External(structure(list(name = "CppMethod__invoke_notvoid", 
       address = <pointer: 0x5634589acc90>, dll = structure(list(
           name = "Rcpp", path = "/home/ken/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/libs/Rcpp.so", 
           dynamicLookup = TRUE, handle = <pointer: 0x5634674b4850>, 
           info = <pointer: 0x56344aead480>), class = "DLLInfo"), 
       numParameters = -1L), class = c("ExternalRoutine", "NativeSymbolInfo"
   )), <pointer: 0x56346ed71e90>, <pointer: 0x56346ebf4f70>, .pointer, 
       ...)
5: f$pscore_nni(INDEX[, 1L:4L])
4: fitch_nni(tree, f)
3: optim.fitch(tree = tree, data = data, trace = trace, rearrangements = rearrangements, 
       ...)
2: optim.parsimony(tree, bs_data, trace = trace, method = method, 
       rearrangements = rearrangements, ...)
1: phangorn::pratchet(data, trace = FALSE)

**Comment by KlausVigo** [comment]
@kbhoehn, 
I will look into this!

**Comment by KlausVigo** [comment]
@kbhoehn, I hope I fixed now also the second bug. Thanks again for reporting
